name: virga_shop
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
   

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0
  http: ^0.11.3+16
  font_awesome_flutter: ^8.0.1
  carousel_pro: "^0.0.13"
  url_launcher: "^3.0.2"
  image_picker: "^0.4.5"
  flutter_svg: "^0.5.1"
  flutter_advanced_networkimage: any
  shared_preferences: any
  cached_network_image: 
    git: https://github.com/Cretezy/flutter_cached_network_image.git
  rxdart: ^0.18.1

  json_annotation: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
 



# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - graphics/brush.png
    - graphics/groceries.png
    - graphics/toothbrush.png
    - graphics/vegetables.png
    - graphics/place1.jpg
    - graphics/cube.png
    - graphics/logo.jpg
    - graphics/logo_trans.png
    - graphics/logo_thump.png

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
  fonts:
    - family: BreeSerif
      fonts:
        - asset: fonts/BreeSerif-Regular.ttf
    - family: Comfortaa
      fonts:
        - asset: fonts/Comfortaa/Comfortaa-Regular.ttf
        - asset: fonts/Comfortaa/Comfortaa-Bold.ttf
          weight: 700
        - asset: fonts/Comfortaa/Comfortaa-Light.ttf
          weight: 300
        